version: '3.1'
services:
  web:
      build: ./docker/web
      links:
      - db
      environment:
      - WORDPRESS_DB_PASSWORD=password
      - APACHE_RUN_USER=www-data
      ports:
      - "8081:80"
      working_dir: /var/www/html
      volumes:
      - './:/var/www/html'
  db:
      image: mysql:5.7
      environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wp_database
      ports:
      - "3301:3306"
      volumes:
      - './mysql_data:/var/lib/mysql'