version: '3.1'
services:
  wordpress:
      image: wordpress
      links:
        - mariadb:mysql
      environment:
        - WORDPRESS_DB_PASSWORD=password
      ports:
        - "8090:80"
      volumes:
        - ./code:/code
        - ./html:/var/www/html
  mariadb:
      image: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=wordpress_db
      ports:
        - "3390:3306"
      volumes:
        - ./database:/var/lib/mysql